module.exports = {
    "dependencies": {
        "@ant-design/icons-react-native": "^1.0.2",
        "@ant-design/react-native": "^3.1.0",
        "babel-plugin-transform-runtime": "^6.23.0",
        "dva-core": "^1.3.0",
        "dva-loading": "^2.0.5",
        "lottie-react-native": "^3.1.0",
        "moment": "^2.20.1",
        "prop-types": "^15.6.0",
        "react": "16.4.1",
        "react-native": "^0.55.4",
        "react-native-amap-geolocation": "^1.0.4",
        "react-native-android-permissions": "^1.0.2",
        "react-native-app-intro-slider": "^0.2.4",
        "react-native-fast-image": "^4.0.14",
        "react-native-image-crop-picker": "^0.19.3",
        "react-native-image-pan-zoom": "^2.1.2",
        "react-native-image-zoom-viewer": "^2.1.3",
        "react-native-largelist-v3": "^3.0.10",
        "react-native-material-dropdown": "^0.11.0",
        "react-native-parallax-scroll-view": "^0.20.1",
        "react-native-simple-dialogs": "^1.1.0",
        "react-native-splash-screen": "^3.2.0",
        "react-native-spring-scrollview": "^2.0.14",
        "react-native-upgrade-android": "^1.0.0",
        "react-native-vector-icons": "^4.6.0",
        "react-native-wechat": "^1.9.10",
        "react-navigation": "^2.12.1",
        "react-navigation-redux-helpers": "^2.0.5",
        "react-redux": "^5.0.7"
      },
    "devDependencies": {
        "babel-eslint": "^8.0.3",
        "babel-jest": "^21.2.0",
        "babel-plugin-import": "^1.6.3",
        "babel-plugin-transform-decorators-legacy": "^1.3.4",
        "babel-preset-react-native": "^4.0.0",
        "eslint": "^4.13.0",
        "eslint-config-airbnb": "^16.1.0",
        "eslint-config-prettier": "^2.9.0",
        "eslint-plugin-babel": "^4.1.2",
        "eslint-plugin-import": "^2.8.0",
        "eslint-plugin-jsx-a11y": "^6.0.2",
        "eslint-plugin-prettier": "^2.3.1",
        "eslint-plugin-react": "^7.5.1",
        "husky": "^0.14.3",
        "jest": "^21.2.1",
        "prettier": "^1.9.1",
        "react-dom": "^16.2.0",
        "react-test-renderer": "^16.2.0"
    },
    "devBundleConfig": {
        "resourceName":"index.ios",
        "codePush":"false" 
    }
}